import 'package:flutter/material.dart';

import '../domain_selection/domains_data.dart';
import 'feed_detail_data.dart';

class FeedCard {
  final String title;
  final String body;
  final String domainId;
  final String domainLabel;
  final IconData icon;
  final Color color;
  final String tag;

  const FeedCard({
    required this.title,
    required this.body,
    required this.domainId,
    required this.domainLabel,
    required this.icon,
    required this.color,
    this.tag = '',
  });

  /// Per-sentence detail strings looked up from the detail data file.
  List<String>? get sentenceDetails => kFeedSentenceDetails[title];
}

const Map<String, List<(String, String, String)>> _cardData = {
  'psychologie': [
    ('L\'effet de simple exposition', 'Plus on est exposé à quelque chose, plus on l\'apprécie. La familiarité crée la sympathie, même sans interaction directe.', '📖 Fait clé'),
    ('Le biais de négativité', 'Le cerveau encode les expériences négatives 3 à 5 fois plus fortement que les positives. Un héritage de survie évolutif.', '📖 Fait clé'),
    ('L\'effet Dunning-Kruger', 'Les personnes peu compétentes surestiment leurs capacités ; les experts les sous-estiment. La vraie connaissance rend humble.', '📖 Fait clé'),
    ('La mémoire est reconstructive', 'On ne retrouve pas un souvenir : on le reconstruit à chaque rappel. La mémoire est vivante, pas un enregistrement fidèle.', '📖 Fait clé'),
    ('La plasticité cérébrale', 'Le cerveau se recâble tout au long de la vie. Chaque apprentissage crée ou renforce des connexions neuronales réelles.', '📖 Fait clé'),
    ('Le biais de confirmation', 'On cherche instinctivement les informations qui confirment ce qu\'on croit déjà. Cherche activement les preuves contraires.', '📖 Fait clé'),
    ('L\'illusion de transparence', 'On croit que nos émotions sont bien plus visibles pour les autres qu\'elles ne le sont réellement. Tu es moins lisible que tu le penses.', '📖 Fait clé'),
    ('L\'effet Zeigarnik', 'Les tâches interrompues restent actives en mémoire de travail. Note ce qui est inachevé pour libérer l\'esprit.', '📖 Fait clé'),
    ('Nommer pour apaiser', 'Mettre un mot sur une émotion — « colère », « honte » — réduit son intensité neurologique. C\'est l\'affect labeling.', '💡 Conseil'),
    ('Le pouvoir des micro-réussites', 'Chaque petite victoire libère de la dopamine et entretient la motivation. Découpe les grands objectifs en mini-étapes.', '💡 Conseil'),
    ('Distancer son point de vue', 'Quand tu es submergé, parle-toi à la 3e personne. Cela active la pensée rationnelle plutôt que l\'émotionnel.', '💡 Conseil'),
    ('Reformuler le problème', 'Changer l\'angle d\'une question change souvent la solution. Demande : « Comment rendre ça plus simple ? »', '💡 Conseil'),
    ('Le principe de charité', 'Avant de répondre à quelqu\'un, reformule son argument dans sa version la plus forte. Cela réduit les conflits inutiles.', '💡 Conseil'),
    ('Pause avant décision', '3 respirations profondes avant une décision importante activent le cortex préfrontal et réduisent les biais impulsifs.', '💡 Conseil'),
    ('Écrire pour traiter', 'Écrire librement sur une expérience difficile pendant 15 min réduit le stress mesuré et améliore la clarté mentale.', '💡 Conseil'),
    ('L\'intention de mise en œuvre', 'Les plans « Si X, alors Y » doublent le taux de réalisation. Sois précis sur le quand et le où.', '💡 Conseil'),
    ('Focus sur le processus', 'Se féliciter pour ses efforts (pas ses résultats) développe un état d\'esprit de croissance et une résilience durable.', '💡 Conseil'),
    ('Le recadrage cognitif', 'Face à une pensée négative, demande : est-ce vrai ? Est-ce utile ? Quelle serait une vision plus juste et équilibrée ?', '🧠 Méthode'),
    ('La fenêtre de Johari', 'Divise ce que tu sais de toi × ce que les autres savent. L\'angle aveugle — vu des autres, pas de toi — est le plus précieux à explorer.', '🧠 Méthode'),
    ('Le journal émotionnel', 'Note chaque soir 1 émotion ressentie, son intensité (1-10) et son déclencheur. Après 4 semaines, les patterns deviennent évidents.', '🧠 Méthode'),
    ('La technique ABC d\'Ellis', 'A = déclencheur, B = croyance automatique, C = conséquence émotionnelle. Identifier et modifier B transforme C.', '🧠 Méthode'),
    ('L\'auto-compassion (Kristin Neff)', 'Traite-toi comme tu traiterais un ami en difficulté : avec chaleur, sans jugement. L\'exigence hostile est contre-productive.', '🧠 Méthode'),
    ('La technique de la chaise vide', 'Parle à voix haute à quelqu\'un d\'imaginaire en face de toi. Change de place, réponds à sa place. Puissant pour résoudre les conflits intérieurs.', '🧠 Méthode'),
    ('La preuve contraire', 'Prends une croyance limitante. Note 3 situations réelles où elle s\'est avérée fausse. Refais cet exercice chaque semaine.', '🏋️ Exercice'),
    ('La lettre à soi-même', 'Écris une lettre à toi d\'il y a 10 ans, puis une à toi dans 10 ans. Observe les valeurs et les peurs qui traversent le temps.', '🏋️ Exercice'),
    ('Observer sans juger', 'Pendant 2 min, observe ta respiration sans chercher à la modifier. Dès que l\'esprit juge, reviens. C\'est tout.', '🏋️ Exercice'),
    ('Cartographie des émotions', 'Sur une semaine, note l\'émotion prédominante à chaque moment clé de ta journée. Cherche les déclencheurs récurrents.', '🏋️ Exercice'),
    ('L\'interview du critique intérieur', 'Quand une voix intérieure te critique, imagine-la comme une personne et demande-lui : « Qu\'essaies-tu de me protéger ? »', '🏋️ Exercice'),
    ('Le scanner corporel', 'Ferme les yeux 3 min. Passe ton attention de la tête aux pieds. Note chaque tension sans chercher à la résoudre.', '🏋️ Exercice'),
    ('Viktor Frankl', '« Entre le stimulus et la réponse, il y a un espace. Dans cet espace se trouve notre liberté de choisir. »', '💬 Citation'),
    ('Carl Jung', '« Qui regarde à l\'extérieur rêve ; qui regarde à l\'intérieur s\'éveille. »', '💬 Citation'),
    ('William James', '« La plus grande découverte de ma génération est que l\'être humain peut changer sa vie en changeant ses attitudes mentales. »', '💬 Citation'),
    ('La règle des 10-10-10', 'Demande-toi : dans 10 min, 10 mois, 10 ans, est-ce que cette décision comptera encore ? Excellent filtre anti-panique.', '⚡ Astuce'),
    ('Sourire active le bien-être', 'Même un sourire forcé envoie un signal positif au cerveau. L\'embodiment fonctionne dans les deux sens.', '⚡ Astuce'),
    ('La posture influence l\'état', 'Se redresser physiquement modifie l\'état émotionnel. Le corps et l\'esprit se co-régulent en permanence.', '⚡ Astuce'),
    ('Tester avant de juger', 'Avant de rejeter une idée ou un comportement nouveau, essaie-le 7 jours. L\'expérience vaut toujours plus que la théorie.', '⚡ Astuce'),
  ],
  'anxiete': [
    ('L\'anxiété est normale', 'L\'anxiété est un mécanisme de survie : elle prépare le corps à agir face au danger. Le problème n\'est pas son existence, mais son intensité.', '📖 Fait clé'),
    ('Le nerf vague', 'Le nerf vague connecte le cerveau aux organes. Activer la branche parasympathique (via la respiration lente) calme tout le système nerveux.', '📖 Fait clé'),
    ('Cortisol chronique', 'Un stress prolongé maintient le cortisol élevé, ce qui altère la mémoire, le système immunitaire et la qualité du sommeil.', '📖 Fait clé'),
    ('L\'anxiété anticipatoire', 'On souffre souvent plus de l\'anticipation que de l\'événement lui-même. Le cerveau amplifie les menaces futures.', '📖 Fait clé'),
    ('L\'hyperventilation amplifie', 'Respirer trop vite en situation de stress aggrave les symptômes physiques. Ralentir la respiration brise ce cercle.', '📖 Fait clé'),
    ('La règle des 90 secondes', 'Une vague émotionnelle dure neurochimiquement 90 secondes. Après, c\'est le mental qui l\'entretient — pas le corps.', '📖 Fait clé'),
    ('L\'évitement renforce la peur', 'Éviter ce qui fait peur maintient et renforce l\'anxiété. L\'exposition progressive est le traitement le plus efficace à long terme.', '📖 Fait clé'),
    ('Respiration 4-7-8', 'Inspire 4 s, retiens 7 s, expire 8 s. Trois cycles suffisent souvent à calmer le système nerveux autonome.', '💡 Conseil'),
    ('Ancrage 5-4-3-2-1', 'Nomme 5 choses visibles, 4 que tu touches, 3 sons, 2 odeurs, 1 goût. Ce protocole ancre dans le présent et sort du mode « menace ».', '💡 Conseil'),
    ('Une pensée n\'est pas un fait', 'Une inquiétude est une hypothèse, pas une vérité. Demande-toi : quelles preuves réelles soutiennent cette pensée ?', '💡 Conseil'),
    ('Bouger pour décharger', '10 min de marche rapide font baisser le cortisol — l\'équivalent d\'un anxiolytique léger sans effets secondaires.', '💡 Conseil'),
    ('Froid sur le visage', 'Plonger le visage dans l\'eau froide 30 s active le réflexe de plongée : la fréquence cardiaque chute rapidement.', '💡 Conseil'),
    ('Nommer l\'anxiété', 'Dire « je ressens de l\'anxiété » plutôt que « je suis anxieux » crée une distance salutaire entre toi et l\'émotion.', '💡 Conseil'),
    ('Limiter les actualités', 'Doomscrolling entretient un état d\'alerte permanent. Fixe une seule plage horaire pour l\'information (ex. 15 min/jour).', '💡 Conseil'),
    ('Reporter l\'inquiétude', 'Dédie 15 min/jour à tes inquiétudes à une heure fixe. Quand une pensée anxieuse arrive hors plage, note-la et dis : « pas maintenant ».', '💡 Conseil'),
    ('L\'exposition graduelle', 'Affronter progressivement ce qui fait peur — en commençant par ce qui anxiétise le moins — désensibilise durablement.', '🧠 Méthode'),
    ('La défusion cognitive (ACT)', 'Au lieu de croire une pensée, observe-la : « J\'ai la pensée que… » Cela réduit son emprise sans chercher à l\'éliminer.', '🧠 Méthode'),
    ('Le STOPP', 'Stop — Take a breath — Observe — Pull back — Proceed. Cinq secondes pour sortir du mode réactif.', '🧠 Méthode'),
    ('La méthode DARE', 'Défier la peur, l\'Accepter, Répondre avec confiance, s\'Engager dans la vie. Un cadre pour transformer l\'évitement en confrontation.', '🧠 Méthode'),
    ('Respiration carrée', 'Inspire 4 s, retiens 4 s, expire 4 s, retiens 4 s. Répète 4 fois. Utilisé par les forces spéciales pour garder le calme sous pression.', '🏋️ Exercice'),
    ('Journal des inquiétudes', 'Écris tes peurs du jour. À côté, note la probabilité réelle (0-100 %) et ce que tu ferais si ça arrivait. La peur perd son flou.', '🏋️ Exercice'),
    ('Relaxation musculaire progressive', 'Contracte chaque groupe musculaire 5 s, puis relâche 10 s, de bas en haut. 15 min pour un calme profond.', '🏋️ Exercice'),
    ('La visualisation positive', 'Ferme les yeux, imagine-toi traverser sereinement la situation que tu redoutes. Le cerveau ne fait pas toujours la différence.', '🏋️ Exercice'),
    ('Le défi de l\'action inverse', 'Quand tu veux éviter quelque chose par peur, fais exactement l\'inverse (si c\'est raisonnable). L\'évitement nourrit l\'anxiété.', '🏋️ Exercice'),
    ('La lettre à l\'anxiété', 'Écris une lettre à ton anxiété comme si c\'était une personne : « Tu essaies de m\'aider, mais voici pourquoi tu te trompes... »', '🏋️ Exercice'),
    ('Seneca', '« Nous souffrons plus en imagination que dans la réalité. »', '💬 Citation'),
    ('Mark Twain', '« J\'ai eu beaucoup de problèmes dans ma vie, dont la plupart n\'ont jamais eu lieu. »', '💬 Citation'),
    ('Epictète', '« Ce n\'est pas la réalité qui nous trouble, mais l\'idée que nous nous en faisons. »', '💬 Citation'),
    ('Frapper le sol des pieds', 'Appuie fort les deux pieds au sol pendant 30 s. La sensation proprioceptive ancre dans le présent immédiatement.', '⚡ Astuce'),
    ('L\'humming (fredonner)', 'Fredonner active le nerf vague via les vibrations du larynx. 2 min suffisent à calmer le système nerveux.', '⚡ Astuce'),
    ('Changer de pièce', 'Un changement d\'environnement physique brise le cercle de rumination. Sortir dehors 5 min peut suffire.', '⚡ Astuce'),
    ('Allonger l\'expiration', 'Faire durer l\'expiration 2× plus longtemps que l\'inspiration active la branche parasympathique en moins d\'une minute.', '⚡ Astuce'),
    ('Routine matinale stable', 'L\'imprévisibilité aggrave l\'anxiété. Une routine matinale fixe (même courte) donne un sentiment de contrôle dès le réveil.', '⚡ Astuce'),
  ],
  'productivite': [
    ('Le multitâche n\'existe pas', 'Le cerveau ne fait pas deux choses en parallèle : il bascule rapidement de l\'une à l\'autre. Ce coût de commutation réduit l\'efficacité de 40 %.', '📖 Fait clé'),
    ('La loi de Parkinson', 'Le travail s\'étire pour remplir le temps disponible. Fixer des délais courts augmente la concentration et l\'efficacité.', '📖 Fait clé'),
    ('La loi de Hofstadter', 'Tout prend plus longtemps que prévu, même en tenant compte de cette loi. Ajoute systématiquement 30 % au temps estimé.', '📖 Fait clé'),
    ('Le pic d\'attention', 'La plupart des gens ont 90 à 120 min de concentration profonde le matin. Après, la capacité cognitive décline progressivement.', '📖 Fait clé'),
    ('L\'ego depletion', 'Chaque décision prise dans la journée réduit l\'énergie mentale disponible. Automatise les décisions sans enjeu pour préserver la vraie focus.', '📖 Fait clé'),
    ('La règle 80/20 (Pareto)', '80 % des résultats proviennent de 20 % des efforts. Identifier ces 20 % est la tâche la plus rentable de ta journée.', '📖 Fait clé'),
    ('Le coût des notifications', 'Une notification coupe le flux de travail et prend en moyenne 23 min pour retrouver le niveau de concentration d\'avant.', '📖 Fait clé'),
    ('La règle des 2 minutes', 'Si une tâche prend moins de 2 min, fais-la maintenant. Sinon, planifie-la. Ce filtre évite l\'accumulation de petites choses.', '💡 Conseil'),
    ('Le time-blocking', 'Réserve des plages horaires dédiées dans ton agenda. Ce qui est planifié a bien plus de chances d\'être fait.', '💡 Conseil'),
    ('La mono-tâche', 'Ferme tous les onglets sauf un. Travaille sur une seule chose jusqu\'à ce qu\'elle soit terminée ou que le temps alloué soit écoulé.', '💡 Conseil'),
    ('Les 3 tâches prioritaires (MIT)', 'Chaque matin, identifie les 3 tâches qui, faites aujourd\'hui, rendraient la journée réussie. Commence par elles avant tout.', '💡 Conseil'),
    ('Bloquer les 90 premières minutes', 'Réserve les 90 premières minutes de ta journée à ton travail le plus important, avant les emails et les notifications.', '💡 Conseil'),
    ('L\'environnement de travail dédié', 'Un espace associé uniquement au travail conditionne le cerveau à entrer plus vite en mode focus.', '💡 Conseil'),
    ('La fin du jour définie', 'Se fixer une heure d\'arrêt (shutdown ritual) préserve la récupération et évite la culpabilité diffuse du « j\'aurais dû faire plus ».', '💡 Conseil'),
    ('Le batching des tâches similaires', 'Regroupe les tâches du même type (emails, appels, administratif). Le cerveau est plus efficace dans le même mode.', '💡 Conseil'),
    ('La technique Pomodoro', '25 min de travail intense, 5 min de pause. Après 4 cycles, une pause longue. Simple, efficace, mesurable.', '🧠 Méthode'),
    ('La matrice d\'Eisenhower', 'Urgent+important → fais. Important+non urgent → planifie. Urgent+non important → délègue. Le reste → élimine.', '🧠 Méthode'),
    ('La méthode GTD (Getting Things Done)', 'Capture tout dans un inbox, clarifie ce que ça implique, organise, révise régulièrement, agis. Un système qui libère l\'esprit.', '🧠 Méthode'),
    ('L\'Eat the Frog', 'Fais ta tâche la plus difficile ou la plus repoussée en premier. Une fois faite, le reste de la journée semble plus facile.', '🧠 Méthode'),
    ('La revue hebdomadaire', 'Chaque dimanche : vide l\'inbox, revois les projets en cours, planifie la semaine. 30 min qui changent tout.', '🧠 Méthode'),
    ('L\'audit de semaine', 'Cette semaine, note ce que tu fais réellement toutes les 30 min. Après 5 jours, tu verras exactement où ton temps part.', '🏋️ Exercice'),
    ('Identifier tes 20 %', 'Liste tes 10 activités principales. Entoure les 2 qui génèrent 80 % de tes résultats. Comment leur donner plus de place ?', '🏋️ Exercice'),
    ('Le shutdown ritual', 'Chaque soir, note les tâches inachevées, la prochaine action pour chacune, puis dis à voix haute : « shutdown complet ».', '🏋️ Exercice'),
    ('Le planning inversé', 'Commence par placer dans ton agenda la récupération, le sport, le social. Puis remplis avec le travail. Ce qui compte tient toujours.', '🏋️ Exercice'),
    ('Le deep work de 90 min', 'Demain matin, éteins téléphone et notifications. Travaille 90 min sur ta priorité absolue. Note comment tu te sens après.', '🏋️ Exercice'),
    ('Peter Drucker', '« Il n\'y a rien de plus inutile que de faire efficacement ce qui ne devrait pas être fait du tout. »', '💬 Citation'),
    ('Cal Newport', '« Les grandes réalisations proviennent de la capacité à faire une chose à la fois, avec une intensité extrême. »', '💬 Citation'),
    ('Warren Buffett', '« La différence entre les gens qui réussissent et ceux qui réussissent vraiment, c\'est que ces derniers disent non à presque tout. »', '💬 Citation'),
    ('Désactiver toutes les notifications', 'Éteins toutes les notifications non essentielles. Ce que tu ne vois pas ne peut pas interrompre ton flux.', '⚡ Astuce'),
    ('La règle du prochain pas', 'Si une tâche est bloquante, demande : quelle est la prochaine action physique, concrète, que je peux faire maintenant ?', '⚡ Astuce'),
    ('Musique instrumentale', 'La musique sans paroles augmente la concentration sur les tâches créatives. Le bruit blanc aide sur les tâches analytiques.', '⚡ Astuce'),
    ('Préparer la veille', 'Écrire sa liste de priorités la veille permet de démarrer sans friction et d\'occuper son esprit pendant le sommeil.', '⚡ Astuce'),
  ],
  'sport': [
    ('Le NEAT compte autant', 'Les calories brûlées hors séance (marcher, bouger, fidgeting) pèsent souvent plus lourd que la séance elle-même. Reste actif toute la journée.', '📖 Fait clé'),
    ('La surcharge progressive', 'Le corps s\'adapte au stimulus. Pour progresser, augmente régulièrement la difficulté : charge, reps, vitesse ou durée.', '📖 Fait clé'),
    ('La récupération, c\'est le progrès', 'Les muscles se renforcent au repos, pas pendant l\'effort. L\'entraînement crée le stimulus ; la récupération crée la progression.', '📖 Fait clé'),
    ('L\'EPOC (afterburn)', 'Après un effort intense, le corps continue de brûler des calories pendant 12 à 48 h. Le HIIT maximise cet effet.', '📖 Fait clé'),
    ('VO2 max et longévité', 'Le VO2 max est l\'un des meilleurs prédicteurs de longévité. L\'entraînement cardio l\'améliore à tout âge — même à 70 ans.', '📖 Fait clé'),
    ('Le sport et le cerveau', '20 min de cardio augmentent le BDNF (facteur de croissance cérébrale), améliorant la mémoire et la plasticité neuronale.', '📖 Fait clé'),
    ('La règle du 1 %', 'Progresser de 1 % chaque semaine donne une amélioration de 68 % en un an. La régularité bat l\'intensité.', '📖 Fait clé'),
    ('Commencer par 2 minutes', 'La vraie barrière est le démarrage. Mets tes chaussures et dis-toi que tu t\'arrêtes après 2 min. Tu continueras presque toujours.', '💡 Conseil'),
    ('La fréquence prime sur la durée', '3 séances de 30 min valent mieux qu\'une séance de 90 min par semaine. La régularité entraîne l\'adaptation.', '💡 Conseil'),
    ('Alterner les groupes musculaires', 'Travailler le haut un jour, le bas l\'autre permet à chaque groupe de récupérer 48 h — temps minimum pour la synthèse protéique.', '💡 Conseil'),
    ('S\'échauffer sérieusement', 'Un échauffement de 10 min (cardio léger + mobilité) réduit le risque de blessure et améliore les performances de la séance.', '💡 Conseil'),
    ('Mesurer pour progresser', 'Note poids, reps, temps ou distance. Les données rendent les progrès visibles et motivent à continuer.', '💡 Conseil'),
    ('Intégrer la mobilité', 'La flexibilité et la mobilité articulaire préviennent les blessures et améliorent la qualité de mouvement. 5 min/jour suffisent.', '💡 Conseil'),
    ('Le sport en dehors du sport', 'Préfère les escaliers, marche pour tes trajets courts, lève-toi toutes les heures. Chaque mouvement compte dans le total.', '💡 Conseil'),
    ('Le HIIT (High Intensity Interval Training)', 'Alternance d\'efforts max (20-30 s) et de récupération active. 15-20 min de HIIT ≈ 40 min de cardio modéré en termes d\'effets.', '🧠 Méthode'),
    ('La périodisation', 'Varier l\'intensité et le volume par blocs (semaines légères/lourdes) évite les plateaux et les blessures par surentraînement.', '🧠 Méthode'),
    ('La méthode 5×5', '5 séries de 5 répétitions sur des mouvements composés (squat, soulevé, développé couché). Idéal pour la force brute.', '🧠 Méthode'),
    ('L\'entraînement en zones cardio', 'Zone 2 (conversation possible) = endurance de base. Zone 4-5 = VO2 max. Alterner les deux est le secret des athlètes d\'endurance.', '🧠 Méthode'),
    ('Le défi des 7 jours', 'Fais 10 min de sport chaque jour pendant 7 jours, peu importe quoi. Note comment ton énergie et ton humeur évoluent.', '🏋️ Exercice'),
    ('Le test des 12 minutes (Cooper)', 'Cours 12 min à allure soutenue et mesure la distance. C\'est un indicateur fiable de ta capacité cardiorespiratoire actuelle.', '🏋️ Exercice'),
    ('Squat de 30 jours', 'Jour 1 : 10 squats. Ajoute 5 squats par jour. Après 30 jours, observe la différence dans ta force et ta posture.', '🏋️ Exercice'),
    ('La marche de 30 min sans téléphone', 'Marche 30 min à allure soutenue aujourd\'hui, sans écran. Note ton niveau d\'énergie et ta clarté mentale après.', '🏋️ Exercice'),
    ('La mobilité matinale', '5 min chaque matin : hanches, épaules, colonne. Ces rotations articulaires réduisent les douleurs et préparent le corps à la journée.', '🏋️ Exercice'),
    ('Le gainage de 3 min', 'Planche frontale 60 s, planche latérale droite 30 s, planche latérale gauche 30 s, planche dos 60 s. Quotidiennement, c\'est transformateur.', '🏋️ Exercice'),
    ('Socrate', '« C\'est une honte pour un homme de vieillir sans voir la beauté et la force dont son corps est capable. »', '💬 Citation'),
    ('Arnold Schwarzenegger', '« Le seul mauvais entraînement est celui qui n\'a pas eu lieu. »', '💬 Citation'),
    ('Préparer sa tenue la veille', 'Poser ses habits de sport la veille réduit la friction du lendemain matin et double les chances de s\'entraîner.', '⚡ Astuce'),
    ('Utiliser les micro-moments', 'Pompes entre deux tâches, squats en attendant le café, escaliers à la place de l\'ascenseur. Tout s\'accumule.', '⚡ Astuce'),
    ('S\'entraîner avec quelqu\'un', 'Un partenaire d\'entraînement augmente l\'assiduité de 65 %. L\'engagement social est l\'un des leviers les plus puissants.', '⚡ Astuce'),
    ('Musique rythmée', 'La musique à 120-140 BPM synchronise le rythme de l\'effort et peut améliorer les performances de 10 à 15 %.', '⚡ Astuce'),
    ('La douche froide après', '30 à 60 s d\'eau froide en fin de séance réduit l\'inflammation musculaire et accélère la récupération.', '⚡ Astuce'),
  ],
  'nutrition': [
    ('Le microbiome intestinal', 'Les 38 000 milliards de bactéries dans l\'intestin influencent l\'humeur, l\'immunité et le poids. La diversité alimentaire les nourrit.', '📖 Fait clé'),
    ('Les protéines rassasient plus', 'Les protéines sont 2 à 3 fois plus rassasiantes que les glucides ou lipides à calories égales. Elles préservent aussi la masse musculaire.', '📖 Fait clé'),
    ('L\'indice glycémique', 'Les aliments à IG élevé font monter puis chuter rapidement la glycémie, entraînant fatigue et fringales. Préfère les aliments à IG bas.', '📖 Fait clé'),
    ('Les fibres sont essentielles', 'Les fibres nourrissent le microbiome, ralentissent l\'absorption du sucre et réduisent le risque de maladies chroniques.', '📖 Fait clé'),
    ('La satiété prend 20 min', 'Le signal de satiété met 20 min à atteindre le cerveau. Manger rapidement conduit à surconsommer systématiquement.', '📖 Fait clé'),
    ('Le sucre caché', 'Les produits ultra-transformés contiennent souvent du sucre ajouté, même les salés. Lire les étiquettes révèle des surprises.', '📖 Fait clé'),
    ('L\'eau avant le repas', 'Boire 500 ml d\'eau 30 min avant un repas réduit l\'apport calorique d\'environ 13 % selon des études contrôlées.', '📖 Fait clé'),
    ('L\'assiette repère', 'Moitié légumes, un quart protéines, un quart féculents complets. Simple, équilibré, applicable à chaque repas.', '💡 Conseil'),
    ('Manger lentement', 'Pose ta fourchette entre chaque bouchée. Mâche correctement. Tu mangeras moins et apprécieras davantage chaque repas.', '💡 Conseil'),
    ('Le batch cooking', 'Cuisiner 2 h le dimanche pour avoir des repas prêts toute la semaine élimine les mauvaises décisions par faim et urgence.', '💡 Conseil'),
    ('Privilégier les aliments entiers', 'Un ingrédient que tu peux imaginer dans la nature est généralement meilleur qu\'un produit transformé. Plus c\'est simple, mieux c\'est.', '💡 Conseil'),
    ('Ne pas acheter ce qu\'on ne veut pas manger', 'La volonté s\'exerce au supermarché, pas à minuit devant le placard. Ne ramène pas chez toi ce que tu ne veux pas manger.', '💡 Conseil'),
    ('Les couleurs dans l\'assiette', 'Viser 5 couleurs différentes de légumes et fruits par jour garantit une diversité de micronutriments sans compter les calories.', '💡 Conseil'),
    ('Les protéines au petit-déjeuner', 'Un petit-déjeuner riche en protéines (œufs, yaourt grec) réduit significativement les fringales en milieu de matinée.', '💡 Conseil'),
    ('Le jeûne intermittent 16:8', 'Jeûner 16 h (dont le sommeil) et manger sur une fenêtre de 8 h améliore la sensibilité à l\'insuline chez la plupart des gens.', '🧠 Méthode'),
    ('La méthode des macros', 'Calculer ses besoins en protéines, glucides et lipides selon son objectif permet de structurer l\'alimentation précisément.', '🧠 Méthode'),
    ('Le journal alimentaire', 'Tenir un journal de tout ce qu\'on mange pendant 2 semaines révèle des habitudes invisibles et des calories oubliées.', '🧠 Méthode'),
    ('La règle 80/20 alimentaire', 'Manger sainement 80 % du temps et se permettre des écarts 20 % est plus durable qu\'un régime strict qui finit par céder.', '🧠 Méthode'),
    ('Le défi légumes 7 jours', 'Ajoute une portion de légume supplémentaire à chaque repas pendant 7 jours. Note les changements d\'énergie et de digestion.', '🏋️ Exercice'),
    ('Cuisiner un nouveau plat sain', 'Choisis une recette saine que tu n\'as jamais faite cette semaine. Cuisiner implique de choisir consciemment ses ingrédients.', '🏋️ Exercice'),
    ('Décrypter 5 étiquettes', 'Prends 5 produits du placard. Lis les étiquettes : sucres ajoutés, additifs, sel. Tu verras ces produits différemment après.', '🏋️ Exercice'),
    ('Le repas sans distraction', 'Mange un repas par jour sans écran. Observe seulement les saveurs et les textures. Note la différence de satiété.', '🏋️ Exercice'),
    ('2 litres d\'eau sur 2 jours', 'Hydrate-toi correctement pendant 2 jours consécutifs. Note ton niveau d\'énergie, ta concentration et ton humeur.', '🏋️ Exercice'),
    ('Hippocrate', '« Que ta nourriture soit ton médicament, et ton médicament ta nourriture. »', '💬 Citation'),
    ('Michael Pollan', '« Mange de la vraie nourriture, pas trop, surtout des végétaux. »', '💬 Citation'),
    ('Manger dans une petite assiette', 'Une assiette plus petite réduit les portions servies sans qu\'on le remarque. L\'effet visuel influence la quantité consommée.', '⚡ Astuce'),
    ('La règle du fruit d\'abord', 'Commence les repas par des légumes ou une salade. Tu arrives moins affamé au reste et consommes plus de micronutriments.', '⚡ Astuce'),
    ('Ne pas faire les courses affamé', 'La faim augmente les achats impulsifs de 40 % et oriente vers des aliments plus caloriques. Mange avant le supermarché.', '⚡ Astuce'),
    ('Cuisiner en musique', 'Cuisiner régulièrement chez soi est l\'un des facteurs les plus constants de bonne alimentation. Rends-le agréable.', '⚡ Astuce'),
  ],
  'relations': [
    ('Le ratio 5:1 de Gottman', 'Les relations solides comptent environ 5 interactions positives pour chaque interaction négative. Dessous de ce ratio, la relation se détériore.', '📖 Fait clé'),
    ('Les 4 cavaliers de l\'Apocalypse', 'Gottman identifie 4 comportements qui prédisent la rupture : critique, mépris, attitude défensive, mur (stonewalling).', '📖 Fait clé'),
    ('Les styles d\'attachement', 'Sécure, anxieux, évitant — les styles d\'attachement se forment dans l\'enfance mais évoluent avec les relations adultes et la thérapie.', '📖 Fait clé'),
    ('Les langages de l\'amour', 'Chacun reçoit l\'affection différemment : mots d\'affirmation, temps de qualité, cadeaux, services rendus, contact physique.', '📖 Fait clé'),
    ('La solitude est mortelle', 'L\'isolement social augmente le risque de mortalité prématurée autant que fumer 15 cigarettes par jour. Les liens comptent.', '📖 Fait clé'),
    ('Les émotions sont contagieuses', 'On « attrape » les émotions des gens autour de nous via les neurones miroirs. S\'entourer de gens positifs a un effet réel et mesurable.', '📖 Fait clé'),
    ('L\'écoute active', 'Reformuler ce que dit l\'autre (« si je comprends bien… ») avant de répondre désamorce les malentendus et montre que tu écoutes vraiment.', '💡 Conseil'),
    ('Demander clairement', 'Exprimer un besoin précis vaut mieux qu\'espérer que l\'autre le devine. La clarté n\'est pas de l\'exigence.', '💡 Conseil'),
    ('Réparer rapidement', 'Dans un conflit, chercher à réparer tôt (une blague, un « je suis désolé ») est plus puissant que d\'avoir raison.', '💡 Conseil'),
    ('Critiquer le comportement, pas la personne', '« Tu as fait X et ça m\'a affecté comme ça » est bien plus efficace que « tu es toujours comme ça ».', '💡 Conseil'),
    ('Le temps de qualité sans écran', '15 min d\'attention pleine valent plus que 3 h à moitié présent. La qualité bat la quantité dans les relations.', '💡 Conseil'),
    ('Exprimer la gratitude', 'Dire à voix haute ce qu\'on apprécie chez l\'autre — régulièrement, précisément — maintient la chaleur dans la relation.', '💡 Conseil'),
    ('Respecter les limites', 'Communiquer ses limites clairement et les respecter chez l\'autre est le fondement d\'une relation saine et durable.', '💡 Conseil'),
    ('La communication non-violente (CNV)', 'Observations + Sentiments + Besoins + Demandes. Un cadre pour exprimer ce qui compte sans déclencher de défense.', '🧠 Méthode'),
    ('La méthode XYZ de Gottman', '« Quand tu fais X dans la situation Y, je ressens Z. » Spécifique, factuel, axé sur le ressenti — pas l\'accusation.', '🧠 Méthode'),
    ('Le rituel de réunion', 'Un moment hebdomadaire dédié (30 min sans distraction) pour faire le point sur la relation : réussites et points à améliorer.', '🧠 Méthode'),
    ('La carte des besoins', 'Liste tes 5 besoins relationnels les plus importants. Partage-les. Demande ceux de l\'autre. La clarté évite les suppositions.', '🧠 Méthode'),
    ('La question profonde', 'Pose chaque semaine une question que tu n\'as jamais posée à l\'autre. Ex. : « Qu\'est-ce qui te fait le plus peur en ce moment ? »', '🏋️ Exercice'),
    ('Le journal de gratitude relationnel', 'Note chaque soir une chose que la personne a faite que tu apprécies. Dans 30 jours, partage le carnet entier avec elle.', '🏋️ Exercice'),
    ('Le bilan de relation', 'Réponds seul à : Est-ce que je me sens vu ? Compris ? En sécurité ? Quels besoins ne sont pas comblés ?', '🏋️ Exercice'),
    ('Identifier ton langage de l\'amour', 'Note les 3 dernières fois où tu as ressenti de l\'amour. Qu\'est-ce qui se passait exactement ? C\'est ton langage principal.', '🏋️ Exercice'),
    ('Le contact sans téléphone', 'Passe 1 h avec quelqu\'un d\'important sans aucun écran. Observe la profondeur différente de la connexion.', '🏋️ Exercice'),
    ('Brené Brown', '« La connexion est pourquoi nous sommes ici. C\'est ce qui donne du sens et du but à nos vies. »', '💬 Citation'),
    ('Carl Rogers', '« Être écouté vraiment, c\'est une des joies les plus extraordinaires qui soit. »', '💬 Citation'),
    ('Antoine de Saint-Exupéry', '« Aimer, ce n\'est pas se regarder l\'un l\'autre, c\'est regarder ensemble dans la même direction. »', '💬 Citation'),
    ('Le câlin de 20 secondes', 'Un câlin de 20 secondes libère de l\'ocytocine — l\'hormone du lien. Ce n\'est pas anodin, c\'est biochimique.', '⚡ Astuce'),
    ('Dire oui avant non', 'Dans les conflits, cherche d\'abord ce sur quoi tu es d\'accord avant d\'exprimer ce qui te dérange. Ça change le ton.', '⚡ Astuce'),
    ('Curiosité plutôt que jugement', 'Remplace « pourquoi tu fais ça ? » (accusatoire) par « qu\'est-ce qui t\'a amené là ? » (curieux).', '⚡ Astuce'),
    ('Mémoriser les détails', 'Retenir et mentionner quelque chose que l\'autre a dit il y a quelques jours montre que tu l\'écoutes vraiment.', '⚡ Astuce'),
  ],
  'sommeil': [
    ('Les cycles de 90 minutes', 'Le sommeil se compose de cycles de ~90 min. Se réveiller en fin de cycle donne un réveil bien plus reposé qu\'en plein milieu.', '📖 Fait clé'),
    ('La mélatonine et la lumière', 'La mélatonine est supprimée par la lumière bleue. Les écrans le soir retardent l\'endormissement de 30 à 90 min.', '📖 Fait clé'),
    ('Le sommeil consolide la mémoire', 'Pendant le sommeil profond, le cerveau transfère les apprentissages de la mémoire à court terme vers la mémoire à long terme.', '📖 Fait clé'),
    ('La dette de sommeil ne se rattrape pas', 'Dormir 10 h le week-end ne compense pas une semaine de 5 h/nuit. La dette chronique altère le métabolisme et les émotions.', '📖 Fait clé'),
    ('La température optimale', 'Le cerveau a besoin que la température corporelle baisse pour s\'endormir. Une chambre à 18-19 °C favorise un sommeil profond.', '📖 Fait clé'),
    ('La caféine et sa demi-vie', 'La caféine a une demi-vie de 5 à 7 h. Un café à 15 h = la moitié de la caféine encore active à 21 h.', '📖 Fait clé'),
    ('Le sommeil et le poids', 'Une nuit courte augmente l\'appétit (ghréline up) et réduit la satiété (leptine down). La privation de sommeil favorise la prise de poids.', '📖 Fait clé'),
    ('La régularité avant tout', 'Se coucher et se lever à heures fixes — même le week-end — est le facteur n°1 d\'un bon sommeil. L\'horloge biologique aime la routine.', '💡 Conseil'),
    ('La lumière du matin', 'S\'exposer à la lumière naturelle dans les 30 min après le réveil cale l\'horloge biologique et facilite l\'endormissement le soir.', '💡 Conseil'),
    ('La sieste courte', '10 à 20 min maximum : au-delà, on entre en sommeil profond et on se réveille groggy. L\'idéal est juste après le repas.', '💡 Conseil'),
    ('La chambre = lieu de sommeil', 'Conditionne ton cerveau : la chambre est pour dormir, pas pour travailler ou scroller. L\'association mentale compte énormément.', '💡 Conseil'),
    ('Éviter l\'alcool le soir', 'L\'alcool aide à s\'endormir mais fragmente le sommeil et supprime le sommeil paradoxal — celui qui restaure le plus.', '💡 Conseil'),
    ('Écrire ses préoccupations avant de dormir', 'Prendre 5 min avant le coucher pour écrire les inquiétudes du lendemain réduit le temps d\'endormissement de 42 %.', '💡 Conseil'),
    ('Le rituel du coucher', 'Un rituel fixe (douche, lecture, tisane) signale au cerveau que l\'heure du sommeil approche et accélère l\'endormissement.', '💡 Conseil'),
    ('Le stimulus control', 'Si tu n\'es pas endormi en 20 min, lève-toi et fais quelque chose de calme dans une autre pièce. Reviens uniquement quand tu as sommeil.', '🧠 Méthode'),
    ('L\'intention paradoxale', 'Au lieu d\'essayer de dormir, essaie de rester éveillé (les yeux fermés, sans bouger). Cela réduit l\'anxiété liée à l\'endormissement.', '🧠 Méthode'),
    ('Le protocole de refroidissement', 'Prends une douche chaude 1 à 2 h avant le coucher. La chute de température corporelle après accélère l\'endormissement.', '🧠 Méthode'),
    ('Le bilan sommeil de 7 jours', 'Note chaque matin : heure de coucher, heure de réveil, qualité (1-10). Les patterns révèlent ce qui perturbe ton sommeil.', '🏋️ Exercice'),
    ('La relaxation de Jacobson', 'Contracte et relâche chaque groupe musculaire de bas en haut, en 15 min. L\'un des somnifères naturels les plus efficaces.', '🏋️ Exercice'),
    ('7 jours sans écrans le soir', 'Cette semaine, éteins tous les écrans 1 h avant de dormir. Note la différence sur la qualité de ton endormissement.', '🏋️ Exercice'),
    ('Calculer ses cycles de sommeil', 'Détermine l\'heure à laquelle tu dois te lever et compte en arrière par tranches de 90 min. Coucher à 22 h ou 23 h 30 pour un réveil à 7 h.', '🏋️ Exercice'),
    ('Matthew Walker', '« Le sommeil est la plus grande superpuissance légale qui améliore presque tous les aspects de ta biologie. »', '💬 Citation'),
    ('Ariana Huffington', '« Le sommeil n\'est pas un luxe. C\'est une nécessité biologique et la fondation d\'une bonne santé. »', '💬 Citation'),
    ('La respiration 4-7-8 pour dormir', 'Inspire 4 s, retiens 7 s, expire 8 s. Répète 4 fois avant de dormir. Le Dr Weil l\'appelle « le tranquillisant naturel ».', '⚡ Astuce'),
    ('Chaussettes chaudes', 'Porter des chaussettes la nuit dilate les vaisseaux des pieds, aidant la redistribution de chaleur centrale et l\'endormissement.', '⚡ Astuce'),
    ('La règle du dernier café à midi', 'Décale progressivement ton dernier café vers midi. Note l\'amélioration du sommeil profond après 1 semaine.', '⚡ Astuce'),
    ('Masque et bouchons d\'oreilles', 'Même de légers bruits nocturnes fragmentent le sommeil sans qu\'on s\'en souvienne. Les bouchons valent l\'essai.', '⚡ Astuce'),
  ],
  'confiance': [
    ('La confiance se construit par l\'action', 'On n\'attend pas d\'avoir confiance pour agir : c\'est l\'action répétée qui construit la confiance. L\'ordre est toujours : agir d\'abord.', '📖 Fait clé'),
    ('Le dialogue interne à la 2e personne', 'Se parler à la 2e personne (« tu peux le faire ») améliore la performance sous pression davantage que « je peux le faire ».', '📖 Fait clé'),
    ('La posture de puissance', 'Tenir une posture expansive 2 min avant une situation stressante augmente le sentiment de confiance et réduit le cortisol.', '📖 Fait clé'),
    ('L\'identité précède le comportement', 'Se définir comme quelqu\'un qui « fait du sport » plutôt que quelqu\'un qui « essaie » change les comportements durablement.', '📖 Fait clé'),
    ('Le syndrome de l\'imposteur est universel', '70 % des personnes ont ressenti le syndrome de l\'imposteur au moins une fois. Les plus compétents le ressentent le plus souvent.', '📖 Fait clé'),
    ('La comparaison sociale détruit', 'Se comparer aux autres sur les réseaux sociaux active les mêmes zones cérébrales que la douleur physique.', '📖 Fait clé'),
    ('Agir avant de se sentir prêt', 'Attendre d\'être prêt est la plus grande illusion. La confiance suit l\'action — elle ne la précède que rarement.', '💡 Conseil'),
    ('Collectionner les preuves', 'Note tes réussites, même petites. La confiance se construit sur des faits réels, pas sur l\'humeur du jour.', '💡 Conseil'),
    ('Le petit défi quotidien', 'Fais chaque jour une chose légèrement inconfortable. Ce muscle de l\'inconfort renforce la confiance en ta capacité à traverser.', '💡 Conseil'),
    ('Reformuler l\'échec', 'Chaque échec est une donnée, pas une sentence. Demande : qu\'est-ce que cette expérience m\'a appris ?', '💡 Conseil'),
    ('Éviter les gens qui diminuent', 'L\'entourage influence directement l\'estime de soi. Identifie les personnes qui te laissent plus grand et celles qui te rapetissent.', '💡 Conseil'),
    ('Parler lentement', 'Parler à un rythme posé est perçu comme un signe de confiance par l\'interlocuteur — et agit aussi sur ton propre état.', '💡 Conseil'),
    ('Les affirmations incarnées', 'Les affirmations fonctionnent si elles sont liées à des valeurs profondes plutôt qu\'à des désirs superficiels.', '🧠 Méthode'),
    ('L\'exposition aux peurs légères', 'Liste tes peurs sociales de 1 à 10. Commence par la n°3. S\'y exposer régulièrement désensibilise et élargit ta zone de confort.', '🧠 Méthode'),
    ('Le journal des succès', 'Chaque soir, note 1 action dont tu es fier, aussi petite soit-elle. En 60 jours, tu auras des preuves irréfutables de ta valeur.', '🧠 Méthode'),
    ('L\'ACT pour la confiance', 'Accepter l\'inconfort plutôt que le fuir, tout en agissant selon ses valeurs. Agir courageusement n\'implique pas d\'être sans peur.', '🧠 Méthode'),
    ('La lettre à l\'imposteur', 'Écris une lettre à ton syndrome de l\'imposteur. Explique-lui ce que tu as réellement accompli et pourquoi il se trompe.', '🏋️ Exercice'),
    ('Le défi de prise de parole', 'Cette semaine, prends la parole dans 3 situations où tu te serais tu. Réunion, conversation, avis en public. Note ce qui se passe.', '🏋️ Exercice'),
    ('La visualisation du meilleur soi', 'Passe 10 min à décrire par écrit toi à ton meilleur : comment tu te comportes, ce que tu ressens, ce que les autres voient.', '🏋️ Exercice'),
    ('Le palmarès personnel', 'Liste tes 10 plus grandes réussites depuis 5 ans. Pour chacune, note les compétences utilisées. Tu en as plus que tu le crois.', '🏋️ Exercice'),
    ('Theodore Roosevelt', '« Faites ce que vous pouvez, avec ce que vous avez, là où vous êtes. »', '💬 Citation'),
    ('Eleanor Roosevelt', '« Personne ne peut vous faire vous sentir inférieur sans votre consentement. »', '💬 Citation'),
    ('Mark Twain', '« Ils ne savaient pas que c\'était impossible, alors ils l\'ont fait. »', '💬 Citation'),
    ('Le regard assuré', 'Maintenir un contact visuel stable lors d\'une conversation est perçu comme un signe de confiance autant par soi que par l\'autre.', '⚡ Astuce'),
    ('La préparation réduit l\'anxiété', '80 % de la confiance en situation vient de la préparation en amont. S\'entraîner à voix haute, seul, est sous-estimé.', '⚡ Astuce'),
    ('Dress for confidence', 'S\'habiller d\'une façon qui te fait te sentir bien change objectivement le comportement et la performance (enclothed cognition).', '⚡ Astuce'),
    ('La gratitude envers soi', 'Termine chaque journée avec : « Qu\'ai-je fait aujourd\'hui dont je suis fier ? » Dis la réponse à voix haute.', '⚡ Astuce'),
  ],
  'bien-etre': [
    ('Le modèle PERMA', 'Le bien-être selon la psychologie positive repose sur 5 piliers : Émotions positives, Engagement, Relations, Sens, Accomplissement.', '📖 Fait clé'),
    ('Les 4 hormones du bonheur', 'Dopamine (récompense), sérotonine (humeur), ocytocine (lien social), endorphines (effort) — chacune peut être stimulée par tes habitudes.', '📖 Fait clé'),
    ('La nature soigne', 'Passer 2 h par semaine en nature réduit significativement le cortisol, la tension artérielle et améliore l\'humeur de façon mesurable.', '📖 Fait clé'),
    ('Le flow state', 'L\'état de flux — absorption totale dans une activité avec un défi légèrement supérieur à ta compétence — est la meilleure expérience possible.', '📖 Fait clé'),
    ('Le sens augmente la résilience', 'Les personnes qui ont un sentiment de sens dans leur vie récupèrent plus vite des épreuves et vivent en moyenne plus longtemps.', '📖 Fait clé'),
    ('Les relations sont n°1', 'L\'étude de Harvard sur 80 ans de suivi identifie la qualité des relations comme le facteur n°1 du bonheur et de la santé.', '📖 Fait clé'),
    ('La cohérence cardiaque', 'Respire 6 fois/min (5 s inspire, 5 s expire) pendant 5 min, 3 fois/jour. Un classique validé pour l\'équilibre du système nerveux.', '💡 Conseil'),
    ('Le scan corporel', 'Passer son attention de la tête aux pieds, une fois par jour, relâche les tensions qu\'on ne remarquait même plus.', '💡 Conseil'),
    ('Les 20 min sans écran', 'Couper toutes notifications 20 min avant une vraie pause recharge l\'attention bien plus qu\'un scroll sur les réseaux.', '💡 Conseil'),
    ('Bouger pour l\'énergie', 'L\'énergie ne se trouve pas dans le repos seul : 20 min de mouvement en crée davantage qu\'il n\'en consomme.', '💡 Conseil'),
    ('Cultiver des micro-joies', 'Identifier et planifier 3 petits plaisirs quotidiens (café, musique, soleil) augmente le niveau de bien-être mesuré.', '💡 Conseil'),
    ('Créer des rituels', 'Les rituels ancrent dans le présent et créent un sentiment de sécurité et de continuité. Ils réduisent la charge cognitive.', '💡 Conseil'),
    ('Donner pour soi', 'Aider les autres active les mêmes zones cérébrales que recevoir des récompenses. L\'altruisme est un investissement personnel.', '💡 Conseil'),
    ('La pleine conscience (MBSR)', 'Le programme de 8 semaines de Kabat-Zinn réduit l\'anxiété, la dépression et la douleur chronique de façon mesurable.', '🧠 Méthode'),
    ('Le yoga nidra', 'Méditation guidée de 20 à 45 min valant l\'équivalent de 2 à 4 h de sommeil selon certaines études. Accessible sans pratique préalable.', '🧠 Méthode'),
    ('Le journaling de gratitude', 'Écrire 3 choses spécifiques pour lesquelles on est reconnaissant chaque soir, pendant 21 jours, recâble le cerveau vers le positif.', '🧠 Méthode'),
    ('La méditation de 5 min', 'Ferme les yeux. Respire lentement. Observe les pensées sans t\'y accrocher pendant 5 min. Si l\'esprit part, reviens à la respiration.', '🏋️ Exercice'),
    ('La promenade de pleine conscience', 'Marche 15 min sans téléphone. Nomme mentalement tout ce que tu vois, entends et sens. Pleine conscience en mouvement.', '🏋️ Exercice'),
    ('La liste de ce qui me ressource', 'Note 10 activités qui te rechargent vraiment. Planifie-en une cette semaine. L\'énergie se gère, elle ne se subit pas.', '🏋️ Exercice'),
    ('Le bilan de fin de journée', 'Chaque soir : 1 moment difficile (et ce que j\'ai appris), 1 moment agréable (et pourquoi il m\'a touché). 5 min, 5 jours.', '🏋️ Exercice'),
    ('Le jeûne des réseaux sociaux', 'Coupe tous les réseaux sociaux pendant 7 jours. Note l\'évolution de ton humeur, de ton attention et de ton sommeil.', '🏋️ Exercice'),
    ('Epictète', '« Ne cherche pas que les événements arrivent comme tu le veux — désire que les événements arrivent comme ils arrivent, et tu seras en paix. »', '💬 Citation'),
    ('Thich Nhat Hanh', '« La seule vie disponible est dans le moment présent. »', '💬 Citation'),
    ('La douche froide le matin', '30 à 60 s d\'eau froide en fin de douche libèrent de la noradrénaline et des endorphines. Un espresso naturel et gratuit.', '⚡ Astuce'),
    ('Plante verte au bureau', 'La présence de végétaux réduit le stress et améliore la concentration dans un espace de travail. Une plante suffit.', '⚡ Astuce'),
    ('Écouter de la musique', 'La musique qu\'on aime libère de la dopamine et réduit le cortisol. 15 min de bonne musique = vraie pause bien-être.', '⚡ Astuce'),
    ('3 gratitudes à voix haute', 'Dire ses gratitudes à voix haute (pas juste y penser) renforce l\'effet sur le système limbique. Le cerveau répond au son.', '⚡ Astuce'),
  ],
  'apprentissage': [
    ('La répétition espacée', 'Revoir une notion à intervalles croissants (1j, 3j, 7j, 21j) ancre la mémoire bien plus que tout relire d\'un coup — c\'est la courbe d\'Ebbinghaus.', '📖 Fait clé'),
    ('L\'effet de test', 'Se réciter de mémoire est 2 à 3 fois plus efficace que relire passivement ses notes. L\'effort de rappel solidifie les souvenirs.', '📖 Fait clé'),
    ('L\'apprentissage entrelacé', 'Alterner des sujets différents dans une même session améliore la rétention à long terme, même si ça semble moins efficace sur le moment.', '📖 Fait clé'),
    ('Le sommeil consolide l\'apprentissage', 'Le sommeil est actif dans la consolidation des souvenirs. Apprendre puis dormir est plus efficace qu\'apprendre deux fois.', '📖 Fait clé'),
    ('L\'erreur est nécessaire', 'L\'apprentissage se produit à la frontière de l\'erreur. Travailler sur ce qu\'on maîtrise déjà n\'entraîne pas de progression réelle.', '📖 Fait clé'),
    ('Le mythe des styles d\'apprentissage', 'L\'idée qu\'on serait « visuel » ou « auditif » n\'est pas validée scientifiquement. La méthode prime sur le « style ».', '📖 Fait clé'),
    ('La pratique délibérée', 'Ce sont les 10 000 heures de pratique délibérée — ciblée, hors zone de confort, avec feedback — qui créent l\'expertise. Pas le temps seul.', '📖 Fait clé'),
    ('Enseigner pour comprendre', 'Expliquer une idée à voix haute révèle instantanément les zones floues. Si tu ne peux pas l\'expliquer simplement, tu ne l\'as pas compris.', '💡 Conseil'),
    ('S\'auto-tester dès le début', 'Teste-toi sur un chapitre AVANT de l\'avoir relu. Le taux d\'erreur élevé signale exactement où apprendre en priorité.', '💡 Conseil'),
    ('Le chunking', 'Le cerveau retient mieux les informations groupées en blocs signifiants. 06 12 34 56 78 est plus facile que 0612345678.', '💡 Conseil'),
    ('Faire des pauses régulières', 'Des pauses de 10 min toutes les 90 min maintiennent les performances cognitives. Les cerveaux qui se reposent apprennent mieux.', '💡 Conseil'),
    ('Apprendre dans différents contextes', 'Réviser dans des endroits différents renforce la mémoire. Le contexte de récupération varie, rendant le souvenir plus robuste.', '💡 Conseil'),
    ('Le principe de l\'effort désirable', 'Ce qui est difficile à apprendre est mieux retenu. L\'aisance est souvent le signe que l\'apprentissage réel ne se produit pas.', '💡 Conseil'),
    ('La méthode Feynman', '1. Choisis un concept. 2. Explique-le comme à un enfant. 3. Repère les lacunes. 4. Reviens à la source. 5. Simplifie encore.', '🧠 Méthode'),
    ('Le système de répétition espacée (SRS)', 'Anki ou tout système de flashcards adaptatif calcule le moment optimal pour te montrer chaque carte. 20 min/jour suffit.', '🧠 Méthode'),
    ('La méthode Cornell', 'Divise chaque page en 3 zones : notes principales, mots-clés, résumé. Force la relecture active et la hiérarchisation.', '🧠 Méthode'),
    ('Le mind mapping', 'Partir d\'un concept central et brancher les idées libère la pensée non-linéaire et révèle des connexions invisibles dans les listes.', '🧠 Méthode'),
    ('La lecture active', 'Lis les titres et sous-titres en premier. Formule des questions. Lis pour y répondre. Résume chaque section avant de continuer.', '🧠 Méthode'),
    ('Le palais de la mémoire', 'Associe les infos à des lieux d\'un trajet mental connu. Les champions de mémorisation l\'utilisent tous.', '🧠 Méthode'),
    ('Enseigner en 3 min', 'Choisis un concept appris cette semaine. Explique-le à voix haute en 3 min comme à un débutant. Repère ce qui bloque.', '🏋️ Exercice'),
    ('Le test à livre fermé', 'Après avoir lu un chapitre, ferme le livre. Note tout ce dont tu te souviens. Ce qui manque = ce qu\'il faut revoir en priorité.', '🏋️ Exercice'),
    ('Créer 10 flashcards', 'Transforme les 10 points clés de ton dernier apprentissage en flashcards (question recto, réponse verso). Teste-toi demain.', '🏋️ Exercice'),
    ('Le résumé en une phrase', 'Résume chaque chapitre ou concept en une seule phrase. Si tu ne peux pas, tu ne l\'as pas encore vraiment compris.', '🏋️ Exercice'),
    ('La pratique délibérée ciblée', 'Identifie ton point faible dans une compétence. Travaille exclusivement sur ce point pendant 20 min avec feedback immédiat.', '🏋️ Exercice'),
    ('Richard Feynman', '« Si tu ne peux pas expliquer quelque chose simplement, c\'est que tu ne le comprends pas vraiment. »', '💬 Citation'),
    ('Benjamin Franklin', '« Un investissement dans la connaissance rapporte toujours les meilleurs intérêts. »', '💬 Citation'),
    ('Apprendre juste avant de dormir', 'Réviser 30 min avant de dormir exploite la consolidation mnésique nocturne. Le cerveau travaille pendant que tu dors.', '⚡ Astuce'),
    ('Enseigner à une peluche', 'Expliquer un concept à n\'importe quel objet révèle les zones non comprises. Le rubber duck debugging des programmeurs.', '⚡ Astuce'),
    ('Résumer en marchant', 'Réviser à voix haute en marchant améliore la rétention grâce à l\'activation physique concomitante.', '⚡ Astuce'),
  ],
  'business': [
    ('La loi de Pareto en business', '80 % du chiffre d\'affaires vient de 20 % des clients. Identifier et servir ces 20 % est la priorité absolue.', '📖 Fait clé'),
    ('Le MVP (Minimum Viable Product)', 'Lancer une version minimale pour tester le marché réel est plus précieux que des mois de préparation en chambre.', '📖 Fait clé'),
    ('La rétention bat l\'acquisition', 'Acquérir un client coûte 5 à 7 fois plus que le fidéliser. La rétention est presque toujours plus rentable.', '📖 Fait clé'),
    ('Le market pull vs tech push', 'Les produits qui réussissent partent d\'un besoin marché réel (pull), non d\'une technologie cherchant un usage (push).', '📖 Fait clé'),
    ('Le réseau comme actif', '80 % des recrutements et 60 % des deals B2B passent par des relations existantes. Le réseau est un actif qui se cultive.', '📖 Fait clé'),
    ('Le product-market fit', 'Tant que le product-market fit n\'est pas atteint (clients qui reviennent et en parlent), tout investissement en croissance est prématuré.', '📖 Fait clé'),
    ('Le pricing est une question de valeur', 'Le prix est rarement le vrai problème : c\'est la valeur perçue. Doubler ses prix peut doubler ses clients si la valeur est là.', '📖 Fait clé'),
    ('Vendre, c\'est écouter', 'Les meilleurs vendeurs parlent moins de 30 % du temps. Ils posent des questions et proposent une solution au besoin entendu.', '💡 Conseil'),
    ('Ne jamais négocier le prix en premier', 'Crée d\'abord de la valeur perçue. Ancre un prix élevé. Le prix se discute toujours mieux une fois la valeur établie.', '💡 Conseil'),
    ('Donner avant de demander', 'Partage de la valeur gratuite (contenu, aide, intro) avant toute demande. Les gens aident ceux qui leur ont d\'abord donné.', '💡 Conseil'),
    ('Chercher le feedback brutal', 'Demande à tes clients : « Qu\'est-ce qui vous empêcherait de recommander ce produit ? » Les réponses gênantes sont les plus utiles.', '💡 Conseil'),
    ('Déléguer pour scaler', 'Un entrepreneur qui fait tout ne peut pas croître. Identifier les tâches à déléguer est une compétence, pas un luxe.', '💡 Conseil'),
    ('Tester avant d\'investir', 'Avant de construire, vends. Une landing page avec un bouton d\'achat révèle la demande réelle mieux que toute étude de marché.', '💡 Conseil'),
    ('Le Business Model Canvas', '9 blocs sur une page : proposition de valeur, segments, canaux, relations, revenus, ressources, activités, partenaires, coûts.', '🧠 Méthode'),
    ('La méthode OKR', 'Objectives & Key Results : 1 objectif ambitieux, 3 résultats mesurables. Alignement et focus sur ce qui compte vraiment.', '🧠 Méthode'),
    ('Le funnel AARRR', 'Acquisition, Activation, Rétention, Recommandation, Revenu. Identifier lequel est cassé en premier est la priorité absolue.', '🧠 Méthode'),
    ('Les jobs-to-be-done (JTBD)', 'Les clients n\'achètent pas un produit : ils l\'« embauchent » pour accomplir un travail. Comprendre le job, c\'est comprendre la vraie demande.', '🧠 Méthode'),
    ('Le pitch en 30 secondes', 'Rédige un pitch : problème, solution, marché, traction. Dis-le à voix haute jusqu\'à ce qu\'il soit fluide et convaincant.', '🏋️ Exercice'),
    ('5 appels clients cette semaine', 'Appelle 5 clients et pose une seule question : « Quel est votre plus grand problème avec X ? » Écoute. Note tout.', '🏋️ Exercice'),
    ('La revue mensuelle des métriques', 'Identifie les 3 indicateurs qui pilotent vraiment ton activité. Suis-les chaque mois. Tout le reste est bruit.', '🏋️ Exercice'),
    ('Le test de la landing page', 'Crée une page simple décrivant ton produit. Lance 50 € de pub. Mesure le taux de clic. Tu as un signal de marché réel.', '🏋️ Exercice'),
    ('Peter Drucker', '« La culture mange la stratégie au petit-déjeuner. »', '💬 Citation'),
    ('Reid Hoffman', '« Si tu n\'as pas honte de la première version de ton produit, c\'est que tu l\'as lancé trop tard. »', '💬 Citation'),
    ('Warren Buffett', '« Le prix, c\'est ce que tu paies. La valeur, c\'est ce que tu reçois. »', '💬 Citation'),
    ('Un email, une action', 'Chaque email envoyé doit avoir une et une seule demande claire. Plusieurs demandes = aucune réponse.', '⚡ Astuce'),
    ('KPIs hebdomadaires', 'Des métriques consultées quotidiennement créent du bruit. Hebdomadairement, elles révèlent des tendances actionnables.', '⚡ Astuce'),
    ('Documenter les process', 'Un process non documenté meurt avec la personne qui le fait. Chaque process répété 3 fois mérite une fiche.', '⚡ Astuce'),
  ],
  'finance': [
    ('Les intérêts composés', 'L\'argent placé génère des intérêts. Ces intérêts génèrent à leur tour des intérêts. L\'effet s\'emballe avec le temps : le plus tôt, le mieux.', '📖 Fait clé'),
    ('L\'inflation érode le cash', 'Garder son argent en cash perd du pouvoir d\'achat chaque année. En France, l\'inflation historique est ~2 % par an.', '📖 Fait clé'),
    ('La règle des 4 %', 'Un portefeuille diversifié supporte un retrait annuel de 4 % sans s\'épuiser sur 30 ans. La base des calculs de retraite anticipée.', '📖 Fait clé'),
    ('Le coût total de possession', 'Le prix d\'achat est rarement le vrai coût : entretien, assurance, temps, énergie, revente. Calcule le coût total avant d\'acheter.', '📖 Fait clé'),
    ('La diversification réduit le risque', 'Répartir ses investissements sur différentes classes d\'actifs et zones géographiques réduit le risque sans réduire le rendement moyen.', '📖 Fait clé'),
    ('Le biais de présent', 'On valorise instinctivement l\'immédiat plus que le futur. Ce biais cognitif explique pourquoi on épargne moins qu\'on le devrait.', '📖 Fait clé'),
    ('Le dollar-cost averaging', 'Investir un montant fixe régulièrement, peu importe le cours, réduit le risque lié au timing et évite les erreurs émotionnelles.', '📖 Fait clé'),
    ('Paie-toi en premier', 'Vire une somme fixe sur un compte épargne/investissement dès que tu reçois ton revenu, avant de dépenser. L\'épargne devient automatique.', '💡 Conseil'),
    ('La règle 50/30/20', '50 % pour les besoins, 30 % pour les envies, 20 % pour l\'épargne. Un repère simple pour équilibrer ton budget.', '💡 Conseil'),
    ('Le fonds d\'urgence en premier', 'Avant d\'investir, constitue un fonds de 3 à 6 mois de dépenses sur un compte accessible. C\'est ton filet de sécurité.', '💡 Conseil'),
    ('Éviter les frais cachés', 'Les frais de gestion de 1,5 % vs 0,2 % sur un ETF coûtent des dizaines de milliers d\'euros sur 20 ans. Les frais sont la seule variable certaine.', '💡 Conseil'),
    ('Ne pas timer le marché', '« Time in the market beats timing the market. » Les meilleurs jours de bourse arrivent souvent après les pires. Rester investi est la stratégie.', '💡 Conseil'),
    ('Augmenter ses revenus', 'Au-delà d\'un seuil, couper les dépenses atteint ses limites. Augmenter ses revenus (compétences, side projects) est aussi une stratégie financière.', '💡 Conseil'),
    ('Le budget base zéro', 'Chaque euro de revenu est affecté à une catégorie jusqu\'à ce que le solde soit zéro. Chaque dépense est intentionnelle.', '🧠 Méthode'),
    ('La méthode des enveloppes', 'Crée des sous-comptes pour chaque objectif (vacances, voiture, retraite). Vire chaque mois. L\'argent ne se mélange pas.', '🧠 Méthode'),
    ('Le portefeuille 3 fonds', '1 ETF actions monde, 1 ETF obligations, 1 fonds monétaire. Simple, diversifié, peu coûteux. Adapté à 80 % des épargnants.', '🧠 Méthode'),
    ('L\'investissement passif (index funds)', 'Les fonds indiciels battent 90 % des gestionnaires actifs sur 15 ans. Investir dans le marché entier à frais bas est la stratégie dominante.', '🧠 Méthode'),
    ('L\'audit financier mensuel', 'Une fois par mois, regarde chaque dépense du mois. Classe-les : nécessaire / utile / superflue. Identifie 1 poste à optimiser.', '🏋️ Exercice'),
    ('Calculer ta valeur nette', 'Actifs (épargne, investissements, biens) moins dettes (crédits, emprunts). Suis ce chiffre trimestriellement. C\'est la vraie mesure.', '🏋️ Exercice'),
    ('Simuler les intérêts composés', 'Utilise un calculateur en ligne : si tu investis X € par mois à Y % sur Z ans. Le résultat est souvent révélateur et motivant.', '🏋️ Exercice'),
    ('Négocier une dépense récurrente', 'Appelle ton opérateur téléphonique ou ton assureur. Demande une réduction. Beaucoup de gens économisent des centaines d\'euros ainsi.', '🏋️ Exercice'),
    ('Warren Buffett', '« Quelqu\'un est assis à l\'ombre aujourd\'hui parce que quelqu\'un a planté un arbre il y a longtemps. »', '💬 Citation'),
    ('Benjamin Franklin', '« Un sou économisé est un sou gagné. »', '💬 Citation'),
    ('Robert Kiyosaki', '« Les riches achètent des actifs. Les pauvres achètent des passifs en croyant que ce sont des actifs. »', '💬 Citation'),
    ('Automatiser les virements', 'Un virement automatique le jour de la paie vers l\'épargne supprime la friction et l\'hésitation. Ce qu\'on ne voit pas, on ne le dépense pas.', '⚡ Astuce'),
    ('La règle des 24 h', 'Avant tout achat non essentiel de plus de 50 €, attends 24 h. Si l\'envie reste, c\'est peut-être un vrai besoin. Souvent, elle passe.', '⚡ Astuce'),
    ('Calculer en heures de travail', 'Avant d\'acheter, convertis le prix en heures de travail. Un vêtement à 200 € = X h de ta vie. Ça change la perspective.', '⚡ Astuce'),
  ],
  'spiritualite': [
    ('La méditation change le cerveau', '8 semaines de pleine conscience épaississent le cortex préfrontal (décision, empathie) et réduisent l\'amygdale (peur, stress).', '📖 Fait clé'),
    ('La gratitude recâble le cerveau', 'Pratiquer la gratitude régulièrement augmente la dopamine et la sérotonine — les mêmes neurotransmetteurs que certains antidépresseurs.', '📖 Fait clé'),
    ('Le sens et la longévité', 'Avoir un sens à sa vie est associé à une réduction du risque de mortalité prématurée de 15 % dans les études longitudinales.', '📖 Fait clé'),
    ('Le moment présent, seule réalité', 'Neurologiquement, le passé n\'existe que comme souvenir et le futur comme anticipation. Seul le présent est expérientiel.', '📖 Fait clé'),
    ('Le silence réduit le stress', 'Des études montrent que 2 min de silence complet réduisent la tension artérielle et le cortisol plus efficacement que la musique relaxante.', '📖 Fait clé'),
    ('Trois gratitudes par jour', 'Chaque soir, note 3 choses spécifiques et positives. Non pas « ma famille » mais « la conversation avec ma sœur ce soir ». La précision compte.', '💡 Conseil'),
    ('Le pouvoir du silence', 'Quelques minutes de silence quotidien réduisent le bruit mental et clarifient les décisions. Difficile au début, transformateur avec le temps.', '💡 Conseil'),
    ('Vivre selon ses valeurs', 'Quand tes actions s\'alignent avec tes valeurs profondes, le sentiment de vide laisse place à la paix. Identifier ses valeurs est une priorité.', '💡 Conseil'),
    ('L\'instant présent', 'La plupart de nos souffrances vivent dans le passé ou le futur. Revenir au présent — corps, sensations, ici — les apaise durablement.', '💡 Conseil'),
    ('Rituel matinal de silence', '10 min de silence, de méditation ou de prière avant tout écran posent le ton de la journée entière.', '💡 Conseil'),
    ('Cultiver le non-attachement', 'Le non-attachement ne signifie pas ne pas désirer, mais ne pas souffrir si le désir n\'est pas satisfait. Une liberté intérieure réelle.', '💡 Conseil'),
    ('La méditation Vipassana', 'Observer les sensations corporelles sans réagir, en conscience. Une des pratiques les plus anciennes et les plus étudiées scientifiquement.', '🧠 Méthode'),
    ('Le stoïcisme pratique', 'Chaque matin : anticipe ce qui pourrait mal se passer. Chaque soir : fais le bilan. Deux outils des stoïciens pour une vie délibérée.', '🧠 Méthode'),
    ('L\'ikigai', 'Trouve l\'intersection de : ce que tu aimes, ce en quoi tu es bon, ce dont le monde a besoin, ce pour quoi tu peux être payé.', '🧠 Méthode'),
    ('Le mémento mori', 'Prendre conscience de sa propre mort clarifie ce qui compte vraiment et rend le présent infiniment plus précieux.', '🧠 Méthode'),
    ('La lecture contemplative', 'Lis lentement un texte profond. Arrête-toi sur ce qui résonne. Médite dessus. Laisse les mots agir plutôt que chercher à tout comprendre.', '🧠 Méthode'),
    ('La méditation de 10 min', 'Installe-toi confortablement. Ferme les yeux. Observe ta respiration pendant 10 min sans chercher à la modifier. Reviens quand l\'esprit part.', '🏋️ Exercice'),
    ('La lettre au futur moi', 'Écris une lettre à toi dans 5 ans. Ce que tu espères, ce que tu souhaites avoir appris, qui tu veux être. Relis dans 5 ans.', '🏋️ Exercice'),
    ('Identifier ses valeurs', 'Liste 10 valeurs importantes. Réduis à 5. Puis à 3. Ces 3 valeurs sont ta boussole. Chaque décision importante passe par elles.', '🏋️ Exercice'),
    ('Le journal du sens', 'Chaque semaine : Qu\'est-ce qui m\'a donné de l\'énergie ? Qu\'est-ce qui en a retiré ? Le sens suit l\'énergie.', '🏋️ Exercice'),
    ('La contemplation de la nature', 'Passe 20 min en nature sans téléphone, sans objectif. L\'émerveillement réduit l\'ego et recentre sur l\'essentiel.', '🏋️ Exercice'),
    ('Marc Aurèle', '« Tu as du pouvoir sur ton esprit, pas sur les événements extérieurs. Réalise cela, et tu trouveras ta force. »', '💬 Citation'),
    ('Rumi', '« Le silence est la langue de Dieu, tout le reste est une mauvaise traduction. »', '💬 Citation'),
    ('Bouddha', '« Il n\'y a pas de chemin vers le bonheur. Le bonheur est le chemin. »', '💬 Citation'),
    ('Le soupir physiologique', 'Deux inspirations rapides suivies d\'une longue expiration — le moyen le plus rapide de calmer le système nerveux.', '⚡ Astuce'),
    ('Un moment de beauté par jour', 'Cherche consciemment un seul moment beau aujourd\'hui : une lumière, un son, un geste. L\'attention au beau se cultive.', '⚡ Astuce'),
    ('Lire un texte de sagesse le matin', '5 min avec Marcus Aurelius ou Rumi plutôt que les actualités. L\'esprit s\'imprègne de ce qu\'il consomme au réveil.', '⚡ Astuce'),
  ],
  'creativite-arts': [
    ('La pensée divergente vs convergente', 'La créativité nécessite d\'abord de la pensée divergente (générer) avant convergente (évaluer). Séparer les deux phases est crucial.', '📖 Fait clé'),
    ('L\'incubation', 'Des idées émergent souvent après une pause : douche, marche, sommeil. Le cerveau en mode default network continue de travailler en arrière-plan.', '📖 Fait clé'),
    ('Le flow (Csikszentmihalyi)', 'L\'état de flux — défi légèrement supérieur à la compétence, objectif clair, feedback immédiat — est la condition optimale de création.', '📖 Fait clé'),
    ('La contrainte libère', 'Les contraintes (temps, format, ressources limitées) forcent à trouver des solutions originales et activent la pensée latérale.', '📖 Fait clé'),
    ('Copier pour comprendre', 'Tous les grands artistes ont commencé par imiter. Copier délibérément les maîtres extrait les principes — puis on s\'en affranchit.', '📖 Fait clé'),
    ('La quantité crée la qualité', 'Produis beaucoup, même imparfait. Les potiers qui font 100 pots apprennent plus que ceux qui passent le même temps sur 1 pot parfait.', '📖 Fait clé'),
    ('Créer tous les jours', 'Une petite création quotidienne entretient l\'élan créatif mieux que de rares sessions intenses. La régularité prime sur l\'inspiration.', '💡 Conseil'),
    ('Commencer sans attendre l\'inspiration', 'L\'inspiration suit l\'action. Commence à écrire, dessiner, jouer — n\'importe quoi. L\'inspiration vient en chemin, pas avant.', '💡 Conseil'),
    ('Tenir un carnet d\'idées', 'Note chaque idée, image ou phrase. Les meilleures idées surgissent rarement au bon moment. Capture tout, trie après.', '💡 Conseil'),
    ('S\'exposer à d\'autres domaines', 'Les meilleures idées naissent souvent de la collision entre deux domaines éloignés. Lis en dehors de ton domaine habituel.', '💡 Conseil'),
    ('Protéger le temps créatif', 'La créativité exige du temps non structuré. Planifie des plages dédiées comme tu planifies des réunions.', '💡 Conseil'),
    ('Critiquer après, pas pendant', 'Pendant la création, coupe le juge intérieur. La phase de création et la phase d\'édition doivent être séparées temporellement.', '💡 Conseil'),
    ('SCAMPER', 'Pour booster une idée : Substitute, Combine, Adapt, Modify, Put to other uses, Eliminate, Reverse. Chaque lettre est un angle créatif.', '🧠 Méthode'),
    ('Les cartes obliques (Brian Eno)', 'Des instructions paradoxales pour sortir d\'une impasse créative. Ex. : « Abandonne les positions normales. »', '🧠 Méthode'),
    ('Le brainstorming inversé', 'Au lieu de « Comment résoudre ce problème ? », demande « Comment l\'aggraver au maximum ? » Inverse ensuite les réponses.', '🧠 Méthode'),
    ('Les Morning Pages (Julia Cameron)', 'Écrire 3 pages à la main dès le réveil, sans filtre ni relecture. Un flux de conscience qui débloque la créativité profonde.', '🧠 Méthode'),
    ('Le prototype en 30 min', 'Crée une version grossière de ton idée en 30 min avec ce que tu as. La concrétiser révèle plus que 5 h de réflexion.', '🧠 Méthode'),
    ('Le dessin de 5 min', 'Dessine quelque chose qui t\'entoure en 5 min. Peu importe la qualité. Observer et retranscrire entraîne un regard créatif.', '🏋️ Exercice'),
    ('100 idées en 10 min', 'Choisis un sujet. Génère 100 idées en 10 min sans juger. Les premières 30 sont évidentes. Les 70 suivantes deviennent intéressantes.', '🏋️ Exercice'),
    ('Copier un maître', 'Choisis une œuvre que tu admires. Reproduis-la fidèlement. Observe ce que tu découvres sur les choix de l\'artiste.', '🏋️ Exercice'),
    ('La contrainte d\'une semaine', 'Fixe-toi une contrainte créative pour 7 jours : photo noir et blanc uniquement, 100 mots/jour, 3 couleurs seulement.', '🏋️ Exercice'),
    ('Le journal visuel', 'Pendant 14 jours, colle une image ou texture qui t\'a touché dans la journée. Aucune raison nécessaire.', '🏋️ Exercice'),
    ('Pablo Picasso', '« Les bons artistes copient, les grands artistes volent. »', '💬 Citation'),
    ('Ira Glass', '« Votre goût est bien meilleur que votre travail. Mais la seule façon de combler l\'écart est de faire du travail. Beaucoup de travail. »', '💬 Citation'),
    ('Chuck Close', '« L\'inspiration est pour les amateurs. Les autres se lèvent et se mettent au travail. »', '💬 Citation'),
    ('Changer d\'outil', 'Si tu es bloqué, change d\'outil : passer de l\'ordinateur au papier débloque souvent une impasse créative.', '⚡ Astuce'),
    ('Sortir de son espace habituel', 'Travailler dans un café ou un parc : le changement de contexte visuel stimule de nouvelles connexions neuronales.', '⚡ Astuce'),
    ('La limitation de temps', 'Se fixer 25 min chrono pour finir une création crée une urgence productive et empêche le perfectionnisme paralysant.', '⚡ Astuce'),
  ],
  'habitudes': [
    ('La boucle habitude', 'Toute habitude suit un cycle : Déclencheur → Routine → Récompense. Modifier ce cycle est la base du changement de comportement.', '📖 Fait clé'),
    ('66 jours en moyenne', 'Contrairement à la légende des 21 jours, une habitude prend en moyenne 66 jours à s\'automatiser selon une étude de l\'UCL.', '📖 Fait clé'),
    ('La volonté s\'épuise', 'La volonté est une ressource limitée qui décline dans la journée. Les bonnes habitudes réduisent la dépendance à la volonté.', '📖 Fait clé'),
    ('L\'environnement prime sur la motivation', 'Le design de l\'environnement influence le comportement plus que la motivation. Rendre une bonne habitude facile est plus puissant.', '📖 Fait clé'),
    ('L\'identité structure les habitudes', 'Les habitudes durables viennent d\'une identité (« je suis quelqu\'un qui fait du sport ») plutôt que d\'un objectif (« je veux perdre 5 kg »).', '📖 Fait clé'),
    ('Chaque habitude renforce un chemin neuronal', 'Chaque répétition renforce la connexion neuronale associée. Chaque abandon l\'affaiblit. Tout compte, dans un sens ou dans l\'autre.', '📖 Fait clé'),
    ('L\'empilement d\'habitudes', 'Accroche une nouvelle habitude à une existante : « Après mon café, je médite 2 min ». La routine existante devient le déclencheur.', '💡 Conseil'),
    ('La règle des 2 minutes', 'Rends l\'habitude si petite qu\'elle prend moins de 2 min à démarrer. Commencer est le plus dur : la petitesse élimine l\'excuse.', '💡 Conseil'),
    ('Soigner son environnement', 'Rendre une bonne habitude facile (visible, accessible) et une mauvaise difficile (masquée, loin) compte plus que la volonté.', '💡 Conseil'),
    ('Ne jamais manquer deux fois', 'Rater un jour arrive. L\'important est de ne pas enchaîner deux jours d\'affilée. Le second manque est le début de l\'abandon.', '💡 Conseil'),
    ('Célébrer immédiatement', 'La récompense doit être immédiate pour renforcer la routine. Un simple « je l\'ai fait ! » dit à voix haute suffit à libérer de la dopamine.', '💡 Conseil'),
    ('Réduire la friction', 'Pose tes habits de sport la veille. Prépare ta bouteille d\'eau le soir. Chaque point de friction éliminé augmente l\'adhérence.', '💡 Conseil'),
    ('Suivre ses habitudes visuellement', 'Un tracker visuel (cases à cocher, calendrier) crée un momentum : la série à maintenir devient elle-même une motivation.', '💡 Conseil'),
    ('Le habit stacking (James Clear)', 'Formule : « Après [HABITUDE ACTUELLE], je vais [NOUVELLE HABITUDE]. » L\'ancrage à une routine existante est puissant et précis.', '🧠 Méthode'),
    ('La carte des habitudes', 'Liste toutes tes habitudes actuelles (matin à soir). Classe chacune : positive / négative / neutre. C\'est ton point de départ réel.', '🧠 Méthode'),
    ('Le temptation bundling', 'Associe une activité que tu aimes (podcast) à une habitude pénible (sport). Tu accèdes au plaisir uniquement pendant l\'effort.', '🧠 Méthode'),
    ('L\'implementation intention', '« Quand [SITUATION], je vais [COMPORTEMENT] dans [LIEU]. » La précision triple le taux de réalisation selon les études.', '🧠 Méthode'),
    ('Le commitment device', 'Rends l\'abandon coûteux à l\'avance : pari avec un ami, paiement à une cause que tu détestes si tu échoues.', '🧠 Méthode'),
    ('L\'audit des habitudes', 'Pendant 3 jours, note chaque action répétée. Classe-les : positive / négative / neutre. Identifie 1 à changer immédiatement.', '🏋️ Exercice'),
    ('La micro-habitude de 7 jours', 'Choisis une habitude si petite qu\'elle semble ridicule (1 pompe, 1 min de méditation). Fais-la 7 jours consécutifs. Observe.', '🏋️ Exercice'),
    ('Redesigner une pièce', 'Réorganise un endroit de ton logement pour que la bonne habitude soit la plus visible et accessible possible.', '🏋️ Exercice'),
    ('Le habit tracker de 30 jours', 'Crée un tableau de 30 jours pour 1 à 3 habitudes. Coche chaque jour. Ne brise pas la chaîne.', '🏋️ Exercice'),
    ('Identifier le déclencheur', 'Note la prochaine fois que tu cèdes à une mauvaise habitude : heure, lieu, état émotionnel. Le déclencheur révèle la solution.', '🏋️ Exercice'),
    ('James Clear', '« Vous ne vous élevez pas au niveau de vos objectifs, vous tombez au niveau de vos systèmes. »', '💬 Citation'),
    ('Aristote', '« Nous sommes ce que nous faisons de manière répétée. L\'excellence n\'est donc pas un acte, mais une habitude. »', '💬 Citation'),
    ('Charles Duhigg', '« Changer une habitude, c\'est changer un choix. Et changer un choix, c\'est changer son identité. »', '💬 Citation'),
    ('Le déclencheur visuel', 'Place un rappel visuel (livre ouvert, tapis de yoga sorti) à l\'endroit où l\'habitude doit avoir lieu.', '⚡ Astuce'),
    ('Lier à l\'identité', 'Remplace « j\'essaie de manger sain » par « je suis quelqu\'un qui prend soin de son corps ». L\'identité guide le comportement.', '⚡ Astuce'),
    ('1 % de mieux chaque jour', '1 % d\'amélioration chaque jour = ×37 en un an. 1 % de régression = quasiment zéro. La direction compte plus que la vitesse.', '⚡ Astuce'),
  ],
};

List<FeedCard> _cardsFor(DomainItem d) {
  final data = _cardData[d.id] ?? const [];
  return [
    for (final (title, body, tag) in data)
      FeedCard(
        title: title,
        body: body,
        domainId: d.id,
        domainLabel: d.label,
        icon: d.icon,
        color: d.color,
        tag: tag,
      ),
  ];
}

List<FeedCard> _interleave(List<List<FeedCard>> lists) {
  final result = <FeedCard>[];
  var i = 0;
  var added = true;
  while (added) {
    added = false;
    for (final l in lists) {
      if (i < l.length) {
        result.add(l[i]);
        added = true;
      }
    }
    i++;
  }
  return result;
}

List<FeedCard> allFeed() => _interleave(kDomains.map(_cardsFor).toList());

List<FeedCard> themedFeed(Set<String> domainIds) {
  if (domainIds.isEmpty) return allFeed();
  final lists = kDomains
      .where((d) => domainIds.contains(d.id))
      .map(_cardsFor)
      .toList();
  return _interleave(lists);
}
